### ISSUE TITLE
Add paranoid property in model

### ISSUE THREAD

**Issue by MalyugaSensei** [tomjschuster/sequelize-ui#105]
Although this is not a critical function, I think it would be important to add the paranoid property to the model

**Comment by tomjschuster** [comment]
Thanks for the feature request. I put up #109 to add support for the paranoid property.

Could you test out the preview build at https://soft-delete.sequelize-ui.pages.dev/ to make sure it's working as expected? (I don't use Sequelize in production anymore and have never used paranoid models.)

**Comment by MalyugaSensei** [comment]
Thank you, this works as expected
