### ISSUE TITLE
the project always is reloading

### ISSUE THREAD

**Issue by jorgetejeda** [tomjschuster/sequelize-ui#52]
Hi, i recently clone this repository, well i decide to play a little bit with the UI but every time i select something the website reload, view code or add a new column the website reload so i check the terminal, it always said that "change detected" and reload.

**Comment by tomjschuster** [comment]
Hi @jorgetejeda, thanks for letting me know about this. While I was not able to recreate, I just upgraded all of the packages to the latest versions (including `webpack` and `webpack-dev-server`) and changed the dev script to enable hot module replacement.

If you pull from master and run:
```sh
npm install
npm run dev
``` 

do you still have the same problem?

**Comment by tomjschuster** [comment]
Closing this out as the site has been completely rewritten. Please reopen if you have any issues running the new site locally.
